# Based on https://docs.codecov.com/docs/codecov-yaml#default-yaml
codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: up
  range: "50...95"
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
